const globalCss = `<style id='stylesheet-for-windy-plugin-da'>.onwindy-plugin-da #open-in-app{display:none}.onwindy-plugin-da.onwindy-plugin-da-info #search{display:none}.onwindy-plugin-da.onwindy-plugin-da-info #plugin-developer-mode{left:500px}#device-mobile .onwindy-plugin-da.onwindy-plugin-da-info #plugin-developer-mode,#device-tablet .onwindy-plugin-da.onwindy-plugin-da-info #plugin-developer-mode{display:none}#device-mobile .onwindy-plugin-da.onwindy-plugin-da-info #logo-wrapper,#device-tablet .onwindy-plugin-da.onwindy-plugin-da-info #logo-wrapper{display:none}#device-mobile .onwindy-plugin-da.onwindy-plugin-da-info .animated-windy-logo,#device-tablet .onwindy-plugin-da.onwindy-plugin-da-info .animated-windy-logo{animation:enter-and-stay 1.5s ease-in-out;display:block;opacity:1}#windy-plugin-da-info{display:none}.onwindy-plugin-da.onwindy-plugin-da-info #windy-plugin-da-info{display:block}#device-mobile .ondetail #windy-plugin-da-info,#device-mobile .onrplanner #windy-plugin-da-info,#device-mobile .onmenu #windy-plugin-da-info,#device-mobile .onstation #windy-plugin-da-info,#device-mobile .onairport #windy-plugin-da-info,#device-mobile .onwebcams-detail #windy-plugin-da-info,#device-mobile .onradiosonde #windy-plugin-da-info,#device-mobile .onexternal-plugins #windy-plugin-da-info,#device-tablet .ondetail #windy-plugin-da-info,#device-tablet .onrplanner #windy-plugin-da-info,#device-tablet .onmenu #windy-plugin-da-info,#device-tablet .onstation #windy-plugin-da-info,#device-tablet .onairport #windy-plugin-da-info,#device-tablet .onwebcams-detail #windy-plugin-da-info,#device-tablet .onradiosonde #windy-plugin-da-info,#device-tablet .onexternal-plugins #windy-plugin-da-info{padding-top:0px !important;padding-bottom:0px !important;max-height:0px !important;overflow:hidden !important}#device-mobile #windy-plugin-da-info,#device-tablet #windy-plugin-da-info{right:8px;width:auto;background-color:#404040ff}#device-mobile #windy-plugin-da-info .closing-x,#device-tablet #windy-plugin-da-info .closing-x{top:0px;right:0px;margin:5px;font-size:20px}#windy-plugin-da-info .hidden{display:none}@media only screen and (min-width:calc(450px + 20px)){#device-tablet #windy-plugin-da-info{width:450px}}.add-scroll-bar{overflow-y:scroll}.add-scroll-bar::-webkit-scrollbar{width:8px;height:8px}.add-scroll-bar::-webkit-scrollbar-thumb{background:rgba(128,128,128,0.5)}.add-scroll-bar::-webkit-scrollbar-track{background:0 0}</style>`;
let globalCssNode;
function insertGlobalCss(){
    if(!document.querySelector("#stylesheet-for-windy-plugin-da")){
        document.head.insertAdjacentHTML('beforeend', globalCss);
        globalCssNode = document.querySelector("#stylesheet-for-windy-plugin-da");
    }
}
function removeGlobalCss(){
    if(globalCssNode){
        globalCssNode.remove();
    }
}
export { globalCssNode, insertGlobalCss, removeGlobalCss };
